name: Placeholder CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Confirm workflow runs
        run: |
          echo "✅ CI/CD workflow is set up!"
          echo "This is a placeholder job. Add lint, tests, and Docker steps later."